import Head from 'next/head'
import BootstrapJS from '../components/Bootstrap'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'


export default function About()
{
    return (
    
        <div className={styles.container}>
          <Head>
            <title>Python Temperature App</title>
            <meta name="description" content="Generated by create next app" />
            <BootstrapJS/>
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar/>
        <body className={styles.aboutContainer}>
    <div className="container" >
  <div className="row">
    <div className="col-sm-4">
      <h2>About Us</h2>
      <p>Project made buy:</p>
      <p>Tymofiy, Christian, Arianne</p>
      <p>Three third year Saint Lambert Champlain-College students</p>

      <h3>Some Links</h3>
      <p>Here are links to the git repos of the project</p>
      <ul className="nav nav-pills flex-column">
        <li className="nav-item">
          <a className="nav-link" href="https://github.com/SmoothWin/PythonWebApp">Backend app</a>
        </li>
        <li className="nav-item">
          <a className="nav-link" href="https://github.com/SmoothWin/python-frontend">Frontend app</a>
        </li>
        <li className="nav-item">
          <a className="nav-link" href="https://github.com/SmoothWin/PythonTemperatureSensor">Rasberry Pi App</a>
        </li>
        
      </ul>
      <hr className="d-sm-none"/>
    </div>
    <div className="col-sm-8">
      <h2>THE RASBERRY PI</h2>
      <h5>Raspberry Pi with DHT sensor</h5>
      <img src="/images/PiImageOne.jpg" width="400" height="300" className={styles.myImg}/>
      <img src="/images/PiImageTwo.jpg" width="400" height="300" className={styles.myImg}/>
      <p>Pi collects data from dht sensor and send it to the backend web app</p>
      <br/>
    
    </div>
  </div>
</div>

        </body>
        </div>
      )
      
    
}