import styles from '../styles/Home.module.css'
import Head from 'next/head'
import { useEffect,useState } from 'react'
import BootstrapJS from '../components/Bootstrap'
import { useRouter } from 'next/router'
import Navbar from '../components/Navbar'
import axios from 'axios'
import Humidity from '../components/Humidity'
import { humidityUrl } from '../constants/urls'

const getUrl = humidityUrl
export default function HumidityPage(props) {
    const router = useRouter()
    const [data, setData] = useState(null)
    const [isMounted, setIsMounted] = useState(false)
    async function getData() {
        try {
            let res = await axios.get(getUrl)
            let dataResponse = await res.data;
            setData(dataResponse)
        } catch (e) {
            console.log(e)
            // router.push("/login")
        }
    }
    useEffect(async () => {
        await getData();
        setIsMounted(true)
    }, [])
    useEffect(async () => {
    }, [isMounted])

    console.log(data)
    let humidityChart = null;
    if (data != null) {
        h_data = data.humidities
        humidityChart = <Humidity humidityData={data.humidities} />
    }
    return (<div className={styles.container}>
        <Head>
            <title>Python Temperature App</title>
            <meta name="description" content="Generated by create next app" />
            <BootstrapJS />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar allData={data} />
        {humidityChart}
    </div>)
}