import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect,useState } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import 'bootstrap/dist/css/bootstrap.min.css';
import {url} from '../constants/urls'

import BootstrapJS from '../components/Bootstrap'
import head from 'next/head'

const mainUrl = url+'/login'

export default function Login() {
    
    const router = useRouter()
    const [isMounted, setIsMounted] = useState(false)
    const [name, setName] = useState("")
    const [pass, setPass] = useState("")

  useEffect(async () => {
    setIsMounted(true)
    try{
      let response = await axios.post(mainUrl, {}, { //done in order to remove the auth cookie if 
        withCredentials: true         //the cookie still exists when the jwt is still expired
      })
      console.log(response)
      if(response.data.message == 'already authorized')
      router.push('/')
    }catch(e){
      
    }
  }, [])
  useEffect(async () => {
    
  }, [isMounted])
  async function handleNameChange(e){
      setName(e.target.value)
  }
  async function handlePasswordChange(e){
      setPass(e.target.value)
  }
  async function handleLogin(e){
    e.preventDefault()
    try{
        let response = await axios.post(mainUrl, {}, {
          withCredentials: true,
            auth:{
                username:name,
                password:pass
            },
        })
        router.push("/")
    } catch(e){
        console.log(e)
    }
  }
  return (
   <div>
       <Head>
       <title>Login - Temperature Python</title>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
       <BootstrapJS/>
     </Head>
     <h3 className="text-center pt-5">Log in</h3>
     <br/><br/>
     <div className="wrapper fadeInDown container">
    <div id="formContent" className="row justify-content-center align-items-center text-center">
       <form onSubmit={handleLogin} className="form col-12 col-sm-8">
             <div className="form-group">
           <label className="text-center input-group-text">Username</label>
           <input id="login" className="fadeIn second form-control" onChange={handleNameChange} type="text"/>
            </div>  
          <br/>
          <div className="form-group">
           <label className="text-center input-group-text">Password</label>
           <input id="password" className="fadeIn third form-control" onChange={handlePasswordChange} type="password"/>
           </div>
           <br/>
           <div className="form-group">
           <button className="fadeIn fourth text-right btn btn-outline-success my-2 my-sm-0" type={"submit"}>Login</button>
           </div>
       </form>
      
   </div>
  </div>
 </div>
  )
}