import styles from '../styles/Home.module.css'
import Head from 'next/head'
import BootstrapJS from '../components/Bootstrap'
import Navbar from '../components/Navbar'
import Status from '../components/Status'
export default function StatusPage(props)
{
    let data = props.data
    console.log(data)
    let statusChart = null;
    if (data != null) {
        statusChart = <Status statusData={data.status} />
    }
    return (<div className={styles.container}>
        <Head>
            <title>Python Temperature App</title>
            <meta name="description" content="Generated by create next app" />
            <BootstrapJS />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar  />
        {statusChart}
    </div>)
}