import styles from '../styles/Home.module.css'
import Head from 'next/head'
import BootstrapJS from '../components/Bootstrap'
import Navbar from '../components/Navbar'
import Temperature from '../components/Temperature'
export default function TemperatureyPage(props)
{
    let data = props.data
    console.log(data)
    let temperatureChart = null;
    if (data != null) {
        temperatureChart = <Temperature temperatureData={data.temperatures} />
    }
    return (<div className={styles.container}>
        <Head>
            <title>Python Temperature App</title>
            <meta name="description" content="Generated by create next app" />
            <BootstrapJS />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar allData={data} />
        {temperatureChart}
    </div>)
}